#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
ctags --tag-relative -aRf"$dir/$$.tags" --langmap=JavaScript:+.jsx --langmap=JavaScript:+.tsx
mv "$dir/$$.tags" "$dir/tags"
